config:
  default: true
  MD013: false # line length
  MD022: false # heading blank lines
  MD031: false # fenced code block blank lines
  MD032: false # list blank lines
  MD033: false # inline HTML
  MD036: false # emphasis as heading
  MD041: false # first line heading level
  MD060: false # table pipe style
  MD024:
    siblings_only: true

ignores:
  - node_modules/**
